export const featuredCars = [
  {
    id: 1,
    make: "BMW",
    model: "X1",
    year: 2025,
    price: 40000,
    images: ["/bmw_x1_2025.jpg"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "SUV",
    mileage: 5000,
    color: "Black",
    wishlisted: false,
  },
  {
    id: 2,
    make: "BMW",
    model: "3 Series",
    year: 2025,
    price: 45000,
    images: ["/bmw_3series_2025.jpg"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 6000,
    color: "White",
    wishlisted: true,
  },
  {
    id: 3,
    make: "BMW",
    model: "4 Series Convertible",
    year: 2024,
    price: 55000,
    images: ["/bmw_4seriesconvertible_2024.jpg"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Convertible",
    mileage: 8000,
    color: "Blue",
    wishlisted: false,
  },
  {
    id: 4,
    make: "Ford",
    model: "Explorer",
    year: 2023,
    price: 36000,
    images: ["/ford_explorer_2023.jpg"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "SUV",
    mileage: 12000,
    color: "Grey",
    wishlisted: true,
  },
  {
    id: 5,
    make: "Ford",
    model: "Focus",
    year: 2023,
    price: 22000,
    images: ["/ford_focus_2023.jpg"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 14000,
    color: "Black",
    wishlisted: true,
  },
  {
    id: 6,
    make: "Ford",
    model: "Fiesta",
    year: 2023,
    price: 11000,
    images: ["/ford_fiesta_2023.jpg"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Hatchback",
    mileage: 15000,
    color: "Blue",
    wishlisted: true,
  },
  {
    id: 7,
    make: "Ford",
    model: "Mustang Convertible",
    year: 2023,
    price: 35000,
    images: ["/ford_mustangconvertible_2023.jpg"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Convertible",
    mileage: 12000,
    color: "Red",
    wishlisted: true,
  },
  {
    id: 8,
    make: "Honda",
    model: "Civic",
    year: 2023,
    price: 26499,
    images: ["/honda_civic_2023.png"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 12000,
    color: "Blue",
    wishlisted: true,
  },
  {
    id: 9,
    make: "Honda",
    model: "Elevate",
    year: 2023,
    price: 18000,
    images: ["/honda_elevate_2023.jpg"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "SUV",
    mileage: 15000,
    color: "Silver",
    wishlisted: true,
  },
  {
    id: 10,
    make: "Honda",
    model: "City",
    year: 2023,
    price: 16000,
    images: ["/honda_city_2023.jpg"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 18000,
    color: "Red",
    wishlisted: false,
  },
  {
    id: 11,
    make: "Honda",
    model: "Jazz",
    year: 2023,
    price: 9000,
    images: ["/honda_jazz_2023.jpg"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Hatchback",
    mileage: 20000,
    color: "Red",
    wishlisted: true,
  },
  {
    id: 12,
    make: "Hyundai",
    model: "Creta",
    year: 2024,
    price: 20000,
    images: ["/hyundai_creta_2024.jpg"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "SUV",
    mileage: 10000,
    color: "White",
    wishlisted: false,
  },
  {
    id: 13,
    make: "Hyundai",
    model: "Verna",
    year: 2024,
    price: 15000,
    images: ["/hyundai_verna_2024.jpg"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 20000,
    color: "Blue",
    wishlisted: true,
  },
  {
    id: 14,
    make: "Hyundai",
    model: "Grand i10 Nios",
    year: 2025,
    price: 8000,
    images: ["/hyundai_grandi10nios_2025.jpg"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Hatchback",
    mileage: 5000,
    color: "White",
    wishlisted: false,
  },
  {
    id: 15,
    make: "Hyundai",
    model: "Ioniq 5",
    year: 2024,
    price: 55000,
    images: ["/hyundai_ioniq5_2024.jpg"],
    transmission: "Automatic",
    fuelType: "Electric",
    bodyType: "SUV",
    mileage: 5000,
    color: "White",
    wishlisted: false,
  },
  {
    id: 16,
    make: "Mahindra",
    model: "XUV700",
    year: 2025,
    price: 25000,
    images: ["/mahindra_xuv700_2025.jpg"],
    transmission: "Automatic",
    fuelType: "Diesel",
    bodyType: "SUV",
    mileage: 8000,
    color: "Red",
    wishlisted: false,
  },
  {
    id: 17,
    make: "Tata",
    model: "Nexon",
    year: 2024,
    price: 12000,
    images: ["/tata_nexon_2024.jpg"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "SUV",
    mileage: 20000,
    color: "Blue",
    wishlisted: true,
  },
  {
    id: 18,
    make: "Tata",
    model: "Tigor",
    year: 2024,
    price: 10000,
    images: ["/tata_tigor_2024.jpg"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 25000,
    color: "Silver",
    wishlisted: false,
  },
  {
    id: 19,
    make: "Tata",
    model: "Tiago",
    year: 2024,
    price: 7000,
    images: ["/tata_tiago_2024.jpg"],
    transmission: "Manual",
    fuelType: "Gasoline",
    bodyType: "Hatchback",
    mileage: 10000,
    color: "Silver",
    wishlisted: false,
  },
  {
    id: 20,
    make: "Tata",
    model: "Curvv EV",
    year: 2025,
    price: 21000,
    images: ["/tata_curvvev_2025.jpg"],
    transmission: "Automatic",
    fuelType: "Electric",
    bodyType: "SUV",
    mileage: 2000,
    color: "Blue",
    wishlisted: true,
  },
  {
    id: 21,
    make: "Tesla",
    model: "Model 3",
    year: 2022,
    price: 42999,
    images: ["/tesla_model3_2022.jpg"],
    transmission: "Automatic",
    fuelType: "Electric",
    bodyType: "Sedan",
    mileage: 8000,
    color: "Red",
    wishlisted: false,
  },
  {
    id: 22,
    make: "Toyota",
    model: "Camry",
    year: 2023,
    price: 28999,
    images: ["/toyota_camry_2023.png"],
    transmission: "Automatic",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    mileage: 15000,
    color: "White",
    wishlisted: false,
  },
];

export const carMakes = [
  { id: 1, name: "Hyundai", image: "/make/hyundai.webp" },
  { id: 2, name: "Honda", image: "/make/honda.webp" },
  { id: 3, name: "BMW", image: "/make/bmw.webp" },
  { id: 4, name: "Tata", image: "/make/tata.webp" },
  { id: 5, name: "Mahindra", image: "/make/mahindra.webp" },
  { id: 6, name: "Ford", image: "/make/ford.webp" },
];

export const bodyTypes = [
  { id: 1, name: "SUV", image: "/body/suv.webp" },
  { id: 2, name: "Sedan", image: "/body/sedan.webp" },
  { id: 3, name: "Hatchback", image: "/body/hatchback.webp" },
  { id: 4, name: "Convertible", image: "/body/convertible.webp" },
];

export const faqItems = [
  {
    question: "How does the test drive booking work?",
    answer:
      "Simply find a car you're interested in, click the 'Test Drive' button, and select an available time slot. Our system will confirm your booking and provide all necessary details.",
  },
  {
    question: "Can I search for cars using an image?",
    answer:
      "Yes! Our AI-powered image search lets you upload a photo of a car you like, and we'll find similar models in our inventory.",
  },
  {
    question: "Are all cars certified and verified?",
    answer:
      "All cars listed on our platform undergo a verification process. We are a trusted dealerships and verified private seller.",
  },
  {
    question: "What happens after I book a test drive?",
    answer:
      "After booking, you'll receive a confirmation email with all the details. We will also contact you to confirm and provide any additional information.",
  },
];
